apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
    - name: java-webservice 
      type: webservice
      properties:
        image: public.ecr.aws/i8e1q7x5/appmod-demo:latest 
        port: 8080
      traits:
        - type: appingress
          properties:
            domain: "*.amazonaws.com" 
            http:
              /*: 8080
