apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmod-node-deployment
spec:
  selector:
    matchLabels:
      app: appmod-node
  replicas: 1
  template:
    metadata:
      labels:
        app: appmod-node
    spec:
      containers:
      - name: appmod-node
        image: <to replace with ECR repo>
        ports:
        - containerPort: 8080
