apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mongodb
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: deployment/addons/mongo
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}