apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-k
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-k
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: deployment/teams/team-k/dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true