apiVersion: batch/v1
kind: Job
metadata:
  namespace: vela-system
  name: install-addon
  labels:
    app: vela-cli
spec:
  template:
    metadata:
      name: install-addon
      labels:
        app: vela-cli
    spec:
      containers:
      - name: install
        image: oamdev/vela-cli:latest
        imagePullPolicy: IfNotPresent
        args:
          - addon
          - enable
          - velaux
      restartPolicy: OnFailure
      serviceAccountName: kubevela-vela-core
